# PRIMARY BACKGROUND
APP_BG ="#50698D"
SIDEBAR_BG = "#0D223F"

# CARDS
CARD_BG =  "#102B53"

# TEXT
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#D0D6E0"

# MAIN ACCENT (buttons)
ACCENT = "#CEB5D4"       # Pink Lavender
ACCENT_TEXT = "#102B53"

# HOVER
ACCENT_HOVER = "#b89ec0"

# SECONDARY
HIGHLIGHT = "#7D9FC0"